### ISSUE TITLE
Getting error when running from pip install

### ISSUE THREAD

**Issue by bitpoke-YT** [bluet/proxybroker2#116]
So i am getting this error on windows with the pip installed version of it. 
With Python 3.11.1 Running this command `proxybroker find --types HTTP HTTPS --lvl High --countries US --strict -l 10`

I get this error
`  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\mrmwg\AppData\Local\Programs\Python\Python311\Scripts\proxybroker.exe\__main__.py", line 7, in <module>
  File "C:\Users\mrmwg\AppData\Local\Programs\Python\Python311\Lib\site-packages\proxybroker\cli.py", line 380, in cli
    proxies = asyncio.Queue(loop=loop)
              ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Queue.__init__() got an unexpected keyword argument 'loop'`

**Comment by ziloka** [comment]
hm I can't seem to reproduce this on linux.. not sure if it would m
[proxybroker2_logs.txt](https://github.com/bluet/proxybroker2/files/10462100/proxybroker2_logs.txt)
atter

**Comment by bitpoke-YT** [comment]
I get in after running `proxybroker find --types HTTP HTTPS --lvl High --countries US --strict -l 10`

**Comment by mthbrown** [comment]
To get rid of this error, just use Python 3.8. You could technically remove [this line](https://github.com/bluet/proxybroker2/blob/master/proxybroker/server.py#L155) to make the error go away, but I've found that **serve** is basically borked in Python 3.10 but works fine on Python 3.8

**Comment by ziloka** [comment]
hm this is related to #113

**Comment by bluet** [comment]
related https://github.com/bluet/proxybroker2/issues/89
